join:
  description: Group players together.
  fields:
    master_id:
      description: Entity ID of the player that should become the coordinator of the group.
      example: "media_player.living_room"
    entity_id:
      description: Name(s) of entities that will join the master.
      example: "media_player.study"

unjoin:
  description: Unjoin the player from a group.
  fields:
    master_id:
      description: Entity ID of the player that is the coordinator of the group.
      example: "media_player.living_room"
    entity_id:
      description: Name(s) of entities that will be unjoined from their group.
      example: "media_player.study"

transfer:
  description: Transfer playback from one roon player to another.
  fields:
    entity_id:
      description: Entity ID of the source player.
      example: "media_player.bedroom"
    transfer_id:
      description: Entity of the destination player.
      example: "media_player.study"
